#server:
#   port : 8480
#
#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1311
#    url: jdbc:mysql://localhost:3306/crud_operation
#
#  jpa:
##    hibernate:
##      naming:
##        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl                    '
##    properties:
##      hibernate:
##        dialect: org.hibernate.dialect.MySQL8Dialect
##        format_sql: true
##    show-sql: true
#
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
#logging:
#  level:
#    org:
#      springframework: ERROR
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE